# Generated by Django 4.2.5 on 2023-11-15 05:48

import CoffeeApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoffeeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='image',
            field=models.ImageField(upload_to=CoffeeApp.models.getFileName),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
